### ISSUE TITLE
Fails to build with rtaudio-6.0: error: use of undeclared identifier 'RtAudioError'; did you mean 'RtAudioErrorType'?

### ISSUE THREAD

**Issue by yurivict** [jacktrip/jacktrip#1117]
```
In file included from jacktrip.p/moc_virtualstudio.cpp:10:
In file included from jacktrip.p/../../src/gui/virtualstudio.h:57:
In file included from jacktrip.p/../../src/gui/vsAudioInterface.h:52:
jacktrip.p/../../src/gui/../RtAudioInterface.h:117:38: error: use of undeclared identifier 'RtAudioError'; did you mean 'RtAudioErrorType'?
    static void RtAudioErrorCallback(RtAudioError::Type type,
                                     ^~~~~~~~~~~~
                                     RtAudioErrorType
/usr/local/include/rtaudio/RtAudio.h:228:6: note: 'RtAudioErrorType' declared here
enum RtAudioErrorType {
     ^
```

Version: 1.10.0
FreeBSD 13.2

**Comment by mikedickey** [comment]
@yurivict yes, that would be the correct new type. Thanks for pointing this out, as I hadn't realized RtAudio 6.0 released. There are more changes required to get it to build & work, which I created [this PR to address](https://github.com/jacktrip/jacktrip/pull/1118).
